import {
    Button,
    HorizontalBox,
    Slider,
    VerticalBox,
    ComboBox,
} from "std-widgets.slint";

export global Eq {
    in property <float> gain_db;
    in property <float> frequency;
    in property <float> log_frequency;
    in property <float> q;

    in property <[string]> eq_types;
    in property <float> min_gain_db;
    in property <float> max_gain_db;
    in property <float> min_frequency;
    in property <float> max_frequency;
    in property <float> min_log_frequency;
    in property <float> max_log_frequency;
    in property <float> min_q;
    in property <float> max_q;
}

export global Callbacks {
    callback request-set-eq-type(int);
    callback request-set-gain-db(float);
    callback request-set-log-frequency(float);
    callback request-set-q(float);
}

component EqControl inherits VerticalBox {
    callback request-set-gain-db(float);
    HorizontalBox {
        Text {
            text: "Type";
            min-width: 160px;
        }

        ComboBox {
            min-width: 160px;
            max-height: 20px;
            model: Eq.eq_types;
            current-index: 0;
            // selected(current-value) => {
            //     root.load-model(self.current-index)
        }
    }

    HorizontalBox {
        Text {
            text: "Gain (dB)";
            min-width: 160px;
        }

        Slider {
            min-width: 160px;
            minimum: Eq.min_gain_db;
            maximum: Eq.max_gain_db;
            value: Eq.gain_db;
            changed(value) => {
                Callbacks.request-set-gain-db(value);
            }
        }

        Text {
            text: Eq.gain_db.to-fixed(2);
        }
    }

    HorizontalBox {
        Text {
            text: "Frequency (Hz)";
            min-width: 160px;
        }

        Slider {
            min-width: 160px;
            minimum: Eq.min_log_frequency;
            maximum: Eq.max_log_frequency;
            value: Eq.log_frequency;
            changed(value) => {
                Callbacks.request-set-log-frequency(value);
            }
        }

        Text {
            text: Eq.frequency.to-fixed(0);
        }
    }

    HorizontalBox {
        Text {
            text: "Q";
            min-width: 160px;
        }

        Slider {
            min-width: 160px;
            minimum: Eq.min_q;
            maximum: Eq.max_q;
            value: Eq.q;
            changed(value) => {
                Callbacks.request-set-q(value);
            }
        }

        Text {
            text: Eq.q.to-fixed(2);
        }
    }
}

export component EqPlotter inherits Window {
    control := EqControl { }
}
