import {
    Button,
    HorizontalBox,
    Slider,
    VerticalBox,
    ComboBox,
    Palette,
} from "std-widgets.slint";

export global Colors {
    in-out property <color> background-color: Palette.background;
}

export global Eq {
    in property <string> eq_type;
    in property <float> gain_db;
    in property <float> frequency;
    in property <float> log_frequency;
    in property <float> q;

    in property <[string]> eq_types;
    in property <float> min_gain_db;
    in property <float> max_gain_db;
    in property <float> min_frequency;
    in property <float> max_frequency;
    in property <float> min_log_frequency;
    in property <float> max_log_frequency;
    in property <float> min_q;
    in property <float> max_q;
}

export global Callbacks {
    pure callback request-set-eq-type(string);
    pure callback request-set-gain-db(float);
    pure callback request-set-log-frequency(float);
    pure callback request-set-q(float);
    pure callback render-eq-plots() -> image;
}

export component EqPlotterUi inherits Window {
    HorizontalLayout {
        VerticalBox {
            HorizontalBox {
                Text {
                    text: "Type";
                    width: 120px;
                }

                ComboBox {
                    width: 160px;
                    max-height: 20px;   // somehow necessary to not make it ridiculously high
                    model: Eq.eq_types;
                    current-value: Eq.eq_type;
                    selected(eq-type) => {
                        Callbacks.request-set-eq-type(eq_type);
                        eq-plot.source = Callbacks.render-eq-plots();
                    }
                }

                Text { }    // just for the layout
            }

            HorizontalBox {
                Text {
                    text: "Gain (dB)";
                    width: 120px;
                }

                Slider {
                    width: 160px;
                    max-height: 20px;   // somehow necessary to not make it ridiculously high
                    minimum: Eq.min_gain_db;
                    maximum: Eq.max_gain_db;
                    value: Eq.gain_db;
                    changed(value) => {
                        Callbacks.request-set-gain-db(value);
                        eq-plot.source = Callbacks.render-eq-plots();
                    }
                }

                Text {
                    text: Eq.gain_db.to-fixed(2);
                }
            }

            HorizontalBox {
                Text {
                    text: "Frequency (Hz)";
                    width: 120px;
                }

                Slider {
                    width: 160px;
                    max-height: 20px;   // somehow necessary to not make it ridiculously high
                    minimum: Eq.min_log_frequency;
                    maximum: Eq.max_log_frequency;
                    value: Eq.log_frequency;
                    changed(value) => {
                        Callbacks.request-set-log-frequency(value);
                        eq-plot.source = Callbacks.render-eq-plots();
                    }
                }

                Text {
                    text: Eq.frequency.to-fixed(0);
                }
            }

            HorizontalBox {
                Text {
                    text: "Q";
                    width: 120px;
                }

                Slider {
                    width: 160px;
                    max-height: 20px;   // somehow necessary to not make it ridiculously high
                    minimum: Eq.min_q;
                    maximum: Eq.max_q;
                    value: Eq.q;
                    changed(value) => {
                        Callbacks.request-set-q(value);
                        eq-plot.source = Callbacks.render-eq-plots();
                    }
                }

                Text {
                    text: Eq.q.to-fixed(2);
                }
            }
        }

        eq-plot := Image {
            source: Callbacks.render-eq-plots();
            width: 1024px;
            height: 1024px;
        }
    }
}
