[package]
name = "eq-plugin-egui"
version = "0.1.0"
edition = "2024"
authors = ["Stephan Widor <stephan@widor.online>"]
license = "GPL-3.0-or-later"
homepage = "https://widor.online"
description = "Simple Eq Plugin"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
egui = { workspace = true }
egui_plot = { workspace = true }
nice-plug = { version = "0.1", features = [
    "assert_process_allocs",
    "standalone",
] }
nice-plug-egui = "0.1"
serde = { workspace = true }


app-lib = { path = "../app-lib" }
audio-lib = { path = "../audio-lib" }
egui-lib = { workspace = true }
